### ISSUE TITLE
討論串在寬螢幕放在議題同一頁，而非新開一頁

### ISSUE THREAD

**Issue by audreyt** [g0v/react.vtaiwan.tw#3]
e.g. http://eviltrout.com/2014/01/22/embedding-discourse.html

**Comment by ghost** [comment]
Ginger 設計稿
https://github.com/g0v/vtaiwan.tw/blob/gh-pages/design/%E4%BB%8B%E7%B4%B9%E8%88%87%E8%A8%8E%E8%AB%962.jpg

https://github.com/g0v/vtaiwan.tw/blob/gh-pages/design/%E4%BB%8B%E7%B4%B9%E8%88%87%E8%A8%8E%E8%AB%96_.jpg

*\* 之後把高亮度的留言標記出來 **
