### ISSUE TITLE
手機上 navigation menu 關掉會回不來

### ISSUE THREAD

**Issue by audreyt** [g0v/react.vtaiwan.tw#8]
https://g0v-tw.slack.com/archives/designer/p1432978061001730

![2015-05-30 5 33 05](https://cloud.githubusercontent.com/assets/20723/7896635/f40fa180-06f1-11e5-997d-5f80a08379bd.png)

**Comment by yhsiang** [comment]
c43253ca887884210cfbea9d561ad881de5a411a 解決蓋到文字問題
navigation 回不來的問題應該也解掉了
